### ISSUE TITLE
我使用npm构建时选择了node_modules文件夹，但是引入vant-webapp时依然找不到目录

### ISSUE THREAD

**Issue by yanbowe** [vue-mini/template#4]
//project.config.json
"packNpmManually": true,
    "packNpmRelationList": [
      {
        "packageJsonPath": "./package.json",
        "miniprogramNpmDistDir": "./node_modules/"
      }
    ],
//app.json
"usingComponents": {
    "van-button": "@vant/weapp/button/index"
  },

[ dist/app.json 文件内容错误] dist/app.json: ["usingComponents"]["van-button"]: "@vant/weapp/button/index" 未找到

**Comment by yanbowe** [comment]
并且
Duplicate of #使用npm构建时提示未找到npm包入口文件

**Comment by yangmingshan** [comment]
- 此模版不需要使用微信开发者工具的 `构建 npm` 功能。
- 要使用 vant-weapp 可能需要对此模版做一些自定义改动。
